<!-- end visko-->
      <hr>

      <footer>
        <p>© Leaf Development 2014</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="./Jumbotron Template for Bootstrap_files/jquery.min.js"></script>
    <script src="./Jumbotron Template for Bootstrap_files/bootstrap.min.js"></script>
  

</body></html>

