

	<!--Sidebar Menu -->
	<div style="position: fixed; left:0px; top: 60px; width=200px; display: block">
	 <ul id="sidebar-nav" class="Menu"> 
	<style type="text/css">a {text-decoration: none; Color: black}</style>
	           	<br/>
	  <font size=4> <b> <a href="privHome.php">Home</a> </b>
			<br/> 
			<br/> 
			<br/> 
			

  		  <b> <a href="searchPipeline.php">Search Pipelines</a>
			<br/> 
			<br/> 
			<br/> 
		 <a href="searchQuery.php">Search Queries</a> 
			<br/> 
			<br/> 
			<br/> 


		 <a href="searchServices.php">Search Services</a>
			<br/> 
			<br/> 
			<br/> 

		 <a href="searchUsers.php">Search Users</a> 
			<br/> 
			<br/> 
			<br/> 

		 <a href="analyzePipelines.php">Analyze Pipelines</a> 
			<br/> 
			<br/> 
			<br/> 

		 <a href="analyzeQueries.php">Analyze Queries</a>
			<br/> 
			<br/> 
			<br/> 


		 <a href="analyzeServices.php"">Analyze Services</a> 

 		</b>


          </ul>
        </div>  </div>
	<!--Explaining VisKo again, text portion of home page-->

