

	<!--Sidebar Menu -->
	<div style="position: fixed; left:0px; top: 60px; display: block">
	 <ul id="sidebar-nav" class="Menu"> 
	<style type="text/css">a {text-decoration: none; Color: black}</style>
            <li> <font size=4> <b> <a href="home.php">Home</a> </b>
            </li>
		<p>&nbsp;</p>
  		   <li><b> <a href="#">Visualize</a>    
			<p>&nbsp;</p>
		<li> <a href="specifyCriteria.php">Search History</a> 
		<p>&nbsp;</p>
		<li> <a href="#">Manage Services</a>
		<p>&nbsp;</p>

		<li> <a href="configureAccount.php">Configure Account</a> 
 		</b>


          </ul>
        </div>  </div>
	<!--Explaining VisKo again, text portion of home page-->

