

	<!--Sidebar Menu -->
	<div style="position: fixed; left:0px; top: 60px; width=200px; display: block">
	 <ul id="sidebar-nav" class="Menu"> 
	<style type="text/css">a {text-decoration: none; Color: black}</style>
	           	<br/>
	  <font size=4> <b> <a href="privHome.php">Home</a> </b>
			<br/> 
			<br/> 
			<br/> 
			

  		  <b> <a href="#">Search Pipelines</a>
			<br/> 
			<br/> 
			<br/> 
		 <a href="#">Search Queries</a> 
			<br/> 
			<br/> 
			<br/> 


		 <a href="#">Search Services</a>
			<br/> 
			<br/> 
			<br/> 

		 <a href="#">Search Users</a> 
			<br/> 
			<br/> 
			<br/> 

		 <a href="#">Analyse Pipeliness</a> 
			<br/> 
			<br/> 
			<br/> 

		 <a href="#">Analyse Queries</a>
			<br/> 
			<br/> 
			<br/> 


		 <a href="#">Analyse Services</a> 

 		</b>


          </ul>
        </div>  </div>
	<!--Explaining VisKo again, text portion of home page-->

