/*
@Authors: Maria Cortes, Rebekah Gruver, Marcela Vazquez
@Date: March 26, 2014
@Description: This file creates a view and funtionality for the Search Users page 
*/


	<!--Sidebar Menu -->
	<div style="position: fixed; left:0px; top: 60px; display: block">
	 <ul id="sidebar-nav" class="Menu"> 
	<style type="text/css">a {text-decoration: none; Color: black}</style>
			<br/> 
			<br/> 
			
             <font size=4> <b> <a href="home.php">Home</a> </b>
			<br/> 
			<br/> 
			<br/> 
         		
  		  <b> <a href="visualize.php">Visualize</a>  
			<br/> 
			<br/> 
			<br/> 
			  
		 <a href="specifyCriteria.php">Search History</a> 
			<br/> 
			<br/> 
			<br/> 

		 <a href="selectOperation.php">Manage Services</a>
			<br/> 
			<br/> 
			<br/> 
			

		 <a href="configureAccount.php">Configure Account</a> 
 		</b>


          </ul>
        </div>  </div>
	<!--Explaining VisKo again, text portion of home page-->

